steps:
  - name: maven:3-eclipse-temurin-17-alpine
    entrypoint: mvn
    dir: percentages
    args: ["test"]
  - name: maven:3-eclipse-temurin-17-alpine
    entrypoint: mvn
    dir: percentages
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    dir: percentages
    args: ["build", "-t", "europe-west1-docker.pkg.dev/$PROJECT_ID/training-lab/percentages", "."]
  - name: gcr.io/cloud-builders/docker
    dir: percentages
    args: [ "push", "europe-west1-docker.pkg.dev/$PROJECT_ID/training-lab/percentages"]
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=petcentages/kube
      - --location=europe-west1
      - --cluster=mycluster
#images: ["europe-west1-docker.pkg.dev/$PROJECT_ID/training-lab/percentages"]