
CREATE TABLE "user" (
	id VARCHAR(63) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE exercise (
	id VARCHAR(63) NOT NULL,
	name VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE record (
	id BIGINT NOT NULL AUTO_INCREMENT ,
	user_id VARCHAR(63) NOT NULL,
	exercise_id VARCHAR(63) NOT NULL,
	record_date DATE NOT NULL,
	"value" DECIMAL(6,2) NOT NULL,
	PRIMARY KEY (id)
) ENGINE = InnoDB;
