steps:
  - name: maven:3-eclipse-temurin-17-alpine
    entrypoint: mvn
    dir: record
    args: ["test"]
  - name: maven:3-eclipse-temurin-17-alpine
    entrypoint: mvn
    dir: record
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    dir: record
    args: ["build", "-t", "europe-west1-docker.pkg.dev/$PROJECT_ID/training-lab/record", "."]
  - name: gcr.io/cloud-builders/docker
    dir: record
    args: [ "push", "europe-west1-docker.pkg.dev/$PROJECT_ID/training-lab/record"]
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=record/kube/
      - --location=europe-west1
      - --cluster=mycluster
      - --namespace=dev
