apiVersion: v1
kind: Service
metadata:
  name: dev-service
spec:
  type: NodePort
  selector:
    app: dev-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-deploy
spec:
  selector:
    matchLabels:
      app: dev-app
  replicas: 1
  strategy:
      type: RollingUpdate
      rollingUpdate:
          maxUnavailable: 1
          maxSurge: 1
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
        - name: percentage-api
          image: europe-west1-docker.pkg.dev/letdoit-389105/training-lab/percentages:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev-service
                port:
                  number: 8080