pipeline {
    agent {
        docker {
            image 'maven:3.9.0-eclipse-temurin-11'
        }
    }

    stages {
        stage('Build') {
            steps {
                echo "Building ${env.BUILD_ID}"
                dir('percentages') {
                    sh 'mvn clean compile package -Dmaven.test.skip=true'
                }
            }
        }
        stage('Test') {
            steps {
                echo "Testing ${env.BUILD_ID}"
                dir('percentages') {
                    sh 'mvn test'
                }
            }
        }
        stage('Deploy') {
            steps {
                echo "Building image ${env.BUILD_ID}"
                dir('percentages') {
                   sh 'mvn spring-boot:build-image -Dmaven.test.skip=true'
                }
            }
        }
    }

}